version: '3.8'

services:
  satellite-unet:
    # image: satellite-net
    build:
      context: .
      dockerfile: dockerfile
    container_name: satellite-net
    shm_size: 8g
    ulimits:
      memlock:
        soft: -1
        hard: -1
    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #         - capabilities: [gpu]
    volumes:
      - ./prepped_data:/workspace
    stdin_open: true
    tty: true
    restart: unless-stopped